# Copyright (c) 2026 KHZ-beep
# SPDX-License-Identifier: MIT
"""Allowlist public release. Never copy the development build/ or test/ directories."""
from pathlib import Path
import zipfile,hashlib,shutil,subprocess,json,os,re
root=Path(__file__).resolve().parents[1]
version='0.3.2';out=root/'dist';out.mkdir(exist_ok=True)
stage=out/f'AtomWeft-{version}-Windows-x64';app=stage/'app';app.mkdir(parents=True,exist_ok=True)
runtime=root/'build/downloads/python-3.13.16-embed-amd64.zip'
assert hashlib.sha256(runtime.read_bytes()).hexdigest()=='97dae5274cc54867065e8d5a3226e48c35017ed332a0fdb0e27d5b5821961297'
def copy(src,dst):
    dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst)
for name in ['bootstrap.py','chemistry.py','cif_coordination.py','powerpoint.py','server.py','requirements.txt','repair-startup.ps1','repair-startup.cmd']:
    copy(root/name,app/name)
for path in (root/'web').glob('*'):
    if path.suffix in ('.js','.css','.html'):copy(path,app/'web'/path.name)
for name in ['AtomWeftAddIn.cs','install.ps1','uninstall.ps1','build.ps1']:
    copy(root/'addin'/name,app/'addin'/name)
for path in (root/'vendor').rglob('*'):
    if not path.is_file():continue
    relative=path.relative_to(root/'vendor')
    if '__pycache__' in relative.parts or path.suffix in ('.pyc','.pyo') or path.name in ('direct_url.json',):continue
    copy(path,app/'vendor'/relative)
with zipfile.ZipFile(runtime) as z:z.extractall(app/'runtime')
(app/'runtime/python313._pth').write_text('python313.zip\n.\n..\nimport site\n',encoding='ascii')
for name in ['selfcheck.py','uninstall-public.ps1','migrate-legacy.ps1','THIRD_PARTY_NOTICES.md']:
    copy(root/'distribution'/name,app/name)
copy(root/'distribution/README-public.md',app/'README.md')
copy(root/'distribution/README-public.md',stage/'README.md')
for name in ['LICENSE','COPYRIGHT.md']:
    copy(root/name,app/name)
    copy(root/name,stage/name)
copy(root/'distribution/install-public.ps1',stage/'install-public.ps1')
(app/'launch.cmd').write_text('@echo off\ncd /d "%~dp0"\n"%~dp0runtime\\python.exe" -B "%~dp0server.py"\nif errorlevel 1 pause\n',encoding='ascii')
(stage/'Install.cmd').write_text('@echo off\ncd /d "%~dp0"\npowershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0install-public.ps1"\nif errorlevel 1 (pause & exit /b 1)\necho Installed. Open PowerPoint to use AtomWeft.\npause\n',encoding='ascii')
# Windows PowerShell 5.1 requires a BOM to read UTF-8 with non-ASCII characters.
for path in stage.rglob('*.ps1'):
    text=path.read_text(encoding='utf-8-sig');path.write_text(text,encoding='utf-8-sig')
csc=Path(os.environ['WINDIR'])/'Microsoft.NET/Framework64/v4.0.30319/csc.exe'
subprocess.run([str(csc),'/nologo','/target:library','/platform:anycpu','/debug-','/reference:System.Windows.Forms.dll',f'/out:{app / "addin/AtomWeftAddIn.dll"}',str(app/'addin/AtomWeftAddIn.cs')],check=True)
subprocess.run([str(app/'runtime/python.exe'),'-B',str(app/'selfcheck.py')],check=True,cwd=app)
# Remove local-generated caches, if a dependency ignored -B; fail instead of shipping them.
assert not list(app.rglob('*.pyc')), 'Generated bytecode may contain development paths'
files=[p for p in stage.rglob('*') if p.is_file()]
private=[str(root),str(root).replace('\\','/'),os.environ.get('USERNAME',''),os.environ.get('COMPUTERNAME',''),str(Path.home())]
needles=[(value,encoding,value.lower().encode(encoding)) for value in private if len(value)>3 for encoding in ('utf-8','utf-16-le')]
violations=[]
for path in files:
    raw=path.read_bytes().lower()
    for value,encoding,needle in needles:
        # Numeric user names can occur as a substring of a SHA256 hash; require a token boundary.
        pattern=rb'(?<![a-z0-9])'+re.escape(needle)+rb'(?![a-z0-9])' if value==os.environ.get('USERNAME') and encoding=='utf-8' else re.escape(needle)
        if re.search(pattern,raw):violations.append(str(path.relative_to(stage)));break
if violations:raise RuntimeError('Private build identifiers found in: '+', '.join(violations))
manifest={'version':version,'runtime':'Python 3.13.16 x64','files':[{'path':p.relative_to(app).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(app.rglob('*')) if p.is_file()]}
(stage/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=True,indent=2),encoding='utf-8')
archive=out/f'AtomWeft-{version}-Windows-x64.zip'
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
    for path in sorted(stage.rglob('*')):
        if path.is_file():z.write(path,path.relative_to(stage))
setup=out/f'AtomWeft-{version}-Setup.exe'
subprocess.run([str(csc),'/nologo','/target:winexe','/platform:anycpu','/debug-','/reference:System.Windows.Forms.dll','/reference:System.Drawing.dll','/reference:System.IO.Compression.dll','/reference:System.IO.Compression.FileSystem.dll',f'/resource:{archive},payload.zip',f'/out:{setup}',str(root/'distribution/Setup.cs')],check=True)
checksums={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in (archive,setup)}
(out/'SHA256SUMS.txt').write_text(''.join(h+'  '+n+'\n' for n,h in checksums.items()),encoding='ascii')
(out/'public-audit.json').write_text(json.dumps({'version':version,'files_scanned':len(files),'private_identifier_matches':0,'excluded':['development logs','user projects','screenshots','registry backups','python-path.txt','local bytecode'],'artifacts':checksums},indent=2),encoding='utf-8')
print(json.dumps({'files':len(files),'zip_bytes':archive.stat().st_size,'setup_bytes':setup.stat().st_size,'privacy_matches':0}))
